using System;

namespace SDRSharp.Tetra
{
	public enum MmPduType
	{
		D_OTAR,
		D_AUTHENTICATION,
		D_CK_CHANGE_DEMAND,
		D_DISABLE,
		D_ENABLE,
		D_LOCATION_UPDATE_ACCEPT,
		D_LOCATION_UPDATE_COMMAND,
		D_LOCATION_UPDATE_REJECT,
		Reserved8,
		D_LOCATION_UPDATE_PROCEEDING,
		D_ATTACH_DETACH_GROUP_IDENTITY,
		D_ATTACH_DETACH_GROUP_IDENTITY_ACKNOWLEDGEMENT,
		D_MM_STATUS,
		Reserved13,
		Reserved14,
		MM_PDU_FUNCTION_NOT_SUPPORTED
	}
}