using System;

namespace SDRSharp.Tetra
{
	public enum MmPrimitivesULType
	{
		U_AUTHENTICATION,
		U_ITSI_DETACH,
		U_LOCATION_UPDATE_DEMAND,
		U_MM_STATUS,
		U_CK_CHANGE_RESULT,
		U_OTAR,
		U_INFORMATION_PROVIDE,
		U_ATTACH_DETACH_GROUP_IDENTITY,
		U_ATTACH_DETACH_GROUP_IDENTITY_ACK,
		U_TEI_PROVIDE,
		Reserved10,
		U_DISABLE_STATUS,
		Reserved12,
		Reserved13,
		Reserved14,
		MM_PDU_FUNCTION_NOT_SUPPORTED
	}
}