using System;

namespace SDRSharp.Tetra
{
	public enum SnPduType
	{
		SN_ACTIVATE_PDP_CONTEXT_ACCEPT,
		SN_DEACTIVATE_PDP_CONTEXT_ACCEPT,
		SN_DEACTIVATE_PDP_CONTEXT_DEMAND,
		SN_ACTIVATE_PDP_CONTEXT_REJECT,
		SN_UNITDATA,
		SN_DATA,
		SN_DATA_TRANSMIT_REQUEST,
		SN_DATA_TRANSMIT_RESPONSE,
		SN_END_OF_DATA,
		SN_RECONNECT,
		SN_PAGE_REQUEST,
		SN_NOT_SUPPORTED,
		SN_DATA_PRIORITY,
		SN_MODIFY,
		SN_Reserved14,
		SN_Reserved15
	}
}